#ifndef SVMM_ABLATION_H
#define SVMM_ABLATION_H

#ifdef SVMM_ABLATE_CPUID
#define SVMM_ABLATE_CPUID_ENABLED 1
#else
#define SVMM_ABLATE_CPUID_ENABLED 0
#endif

#ifdef SVMM_ABLATE_DYNAMIC_MEMORY
#define SVMM_ABLATE_DYNAMIC_MEMORY_ENABLED 1
#else
#define SVMM_ABLATE_DYNAMIC_MEMORY_ENABLED 0
#endif

#ifdef SVMM_ABLATE_BOOT_PARAMS
#define SVMM_ABLATE_BOOT_PARAMS_ENABLED 1
#else
#define SVMM_ABLATE_BOOT_PARAMS_ENABLED 0
#endif

#ifdef SVMM_ABLATE_E820
#define SVMM_ABLATE_E820_ENABLED 1
#else
#define SVMM_ABLATE_E820_ENABLED 0
#endif

#ifdef SVMM_ABLATE_CMDLINE
#define SVMM_ABLATE_CMDLINE_ENABLED 1
#else
#define SVMM_ABLATE_CMDLINE_ENABLED 0
#endif

#ifdef SVMM_ABLATE_PROTECTED_MODE
#define SVMM_ABLATE_PROTECTED_MODE_ENABLED 1
#else
#define SVMM_ABLATE_PROTECTED_MODE_ENABLED 0
#endif

#ifdef SVMM_ABLATE_UART
#define SVMM_ABLATE_UART_ENABLED 1
#else
#define SVMM_ABLATE_UART_ENABLED 0
#endif

#if SVMM_ABLATE_CPUID_ENABLED + SVMM_ABLATE_DYNAMIC_MEMORY_ENABLED + \
    SVMM_ABLATE_BOOT_PARAMS_ENABLED + SVMM_ABLATE_E820_ENABLED + \
    SVMM_ABLATE_CMDLINE_ENABLED + SVMM_ABLATE_PROTECTED_MODE_ENABLED + \
    SVMM_ABLATE_UART_ENABLED > 1
#error "only one Stage 02 ablation may be enabled per binary"
#endif

#ifndef SVMM_VARIANT_NAME
#define SVMM_VARIANT_NAME "baseline"
#endif

#endif
